language: php

services:
- memcached

env:
  global:
  - MEMCACHE_HOST=127.0.0.1
  - MEMCACHE_PORT=11211

sudo: false

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2


cache:
  directories:
  - "$HOME/.composer/cache"

git:
  depth: 1

before_script:
- sh -c 'echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;'

script:
- ./.scripts/run.sh